# SPDX-FileCopyrightText: 2026 TwexAPI Contributors
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
